version: '3'
services:
  ashal_market_bot:
    container_name: ashal_market_bot
    build:
      context: '.'
    restart: unless-stopped
    volumes:
      - ./log/:/home/ashal_market_bot/log
    env_file:
      - config.env
    logging:
      options:
        max-size: 50m
    networks:
      ashal_market_bot:

networks:
  ashal_market_bot:
