version: '3'
services:
  markus:
    container_name: markus
    build:
      context: '.'
    restart: unless-stopped
    volumes:
      - ./log/:/home/markus/log
    env_file:
      - config.env
    network_mode: host
    logging:
      options:
        max-size: 50m
