services:
  markus:
    container_name: markus
    build:
      context: '.'
    restart: unless-stopped
    volumes:
      - ./log/:/home/markus/log
      - ./config/:/home/markus/config
      - ./gacha/data/:/home/markus/gacha/data
    logging:
      options:
        max-size: 50m
